openapi: '3.0.3'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://degree-prerequisite-tracker.onrender.com
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
